using System;
using System.ComponentModel.DataAnnotations;

namespace WebApp4ByJessica.Models
{
    public class Book
    {
        public int Id { get; set; }  // NOT NULL, auto-generated by SQL Server
        public string Title { get; set; } = string.Empty;  // NOT NULL
        public string Author { get; set; } = string.Empty; // NOT NULL
        public string? Isbn { get; set; }                 // Nullable
        public decimal? Price { get; set; }               // Nullable
        public DateTime? PublishedDate { get; set; }      // Nullable
    }
}
